apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: opendistro-kibana
    app: opendistro-kibana
  name: opendistro-kibana
  namespace: opendistro
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: opendistro-kibana
      app: opendistro-kibana
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: opendistro-kibana
        app: opendistro-kibana
    spec:
      containers:
      - env:
        - name: ELASTICSEARCH_URL
          value: https://opendistro-endpoint:9200
        - name: ELASTICSEARCH_HOSTS
          value: https://opendistro-endpoint:9200
        image: opendistro-for-elasticsearch-kibana:0.9.0
        imagePullPolicy: Never
        name: opendistro-kibana
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        ports:
          - containerPort: 5601
            name: kibana-ui
            protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
