apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: opendistro-for-elasticsearch
    app: opendistro-for-elasticsearch
  name: opendistro-for-elasticsearch
  namespace: opendistro
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: opendistro-for-elasticsearch
      app: opendistro-for-elasticsearch
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: opendistro-for-elasticsearch
        app: opendistro-for-elasticsearch
    spec:
      containers:
      - env:
        - name: "discovery.type"
          value: "single-node"
        - name: "cluster.name"
          value: "odfe-cluster"
        - name: "bootstrap.memory_lock"
          value: "true"
        - name: "ES_JAVA_OPTS"
          value: "-Xms512m -Xmx512m"
        image: opendistro-for-elasticsearch:0.9.0
        imagePullPolicy: Never
        name: opendistro-for-elasticsearch
        resources:
        ports:
          - containerPort: 9200
            name: es-endpoint
            protocol: TCP
          - containerPort: 9600
            name: perf-endpoint
            protocol: TCP
        volumeMounts:
          - name: opendistro-data
            mountPath: /usr/share/elasticsearch/data
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
        - name: opendistro-data
          persistentVolumeClaim:
            claimName: opendistro-pvc
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
