apiVersion: v1
kind: PersistentVolume
metadata:
  name: opendistro-pv
  labels:
    type: local
spec:
  storageClassName: opendistro-storage
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/opendistro
  capacity:
    storage: 30Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opendistro-pvc
  namespace: opendistro
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: opendistro-storage
  resources:
    requests:
      storage: 30Gi
