kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: opendistro-storage
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
provisioner: kubernetes.io/minikube-hostpath
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
